gzip -dc ../output/chr10.chunk1.txt.gz > ../output/Autosomes.txt
gzip -dc ../output/chr10.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr10.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr10.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr10.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr10.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr11.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr11.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr11.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr11.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr11.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr11.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr12.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr12.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr12.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr12.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr12.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr12.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr13.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr13.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr13.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr13.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr14.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr14.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr14.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr14.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr15.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr15.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr15.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr15.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr16.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr16.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr16.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr16.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr17.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr17.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr17.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr17.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr18.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr18.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr18.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr18.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr19.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr19.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk10.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk11.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk12.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk8.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr1.chunk9.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr20.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr20.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr20.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr21.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr21.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr22.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr22.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk10.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk11.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk12.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk8.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr2.chunk9.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk8.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr3.chunk9.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk8.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr4.chunk9.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk8.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr5.chunk9.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr6.chunk8.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr7.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr7.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr7.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr7.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr7.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr7.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr7.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr8.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr8.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr8.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr8.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr8.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr8.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr8.chunk7.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr9.chunk1.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr9.chunk2.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr9.chunk3.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr9.chunk4.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr9.chunk5.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip -dc ../output/chr9.chunk6.txt.gz | grep -v CHROM >> ../output/Autosomes.txt
gzip ../output/Autosomes.txt
